### ISSUE TITLE
Change extension name to "Do Not Merge WIP for GitHub"

### ISSUE THREAD

**Issue by sanemat** [sanemat/do-not-merge-wip-for-github#9]
Current extension name is 'github merge caution', but this is ambiguous.
- This is **not** GitHub's product. => for GitHub
- This stop merging 'work in progress' pull request => Do Not Merge WIP (pull request)
## todo
- [x] change repos name
- [x] change app name in source code
- [x] Add change log
- [x] bump version to 1.0.0
- [x] :tada:
